diff --git a/E:/github/ms-react-native-forpatch/ReactAndroid/src/main/jni/first-party/yogajni/BUCK b/E:/github/fb-react-native-forpatch/ReactAndroid/src/main/jni/first-party/yogajni/BUCK
index 7924f31ea..fa379d22d 100644
--- a/E:/github/ms-react-native-forpatch/ReactAndroid/src/main/jni/first-party/yogajni/BUCK
+++ b/E:/github/fb-react-native-forpatch/ReactAndroid/src/main/jni/first-party/yogajni/BUCK
@@ -12,7 +12,6 @@ oss_cxx_library(
         "-Werror",
         "-O3",
         "-std=c++11",
-        '-DANDROIDPLAT',
     ],
     soname = "libyoga.$(ext)",
     visibility = ["PUBLIC"],
