diff --git a/E:/github/ms-react-native-forpatch/ReactAndroid/src/main/java/com/facebook/react/module/processing/BUCK b/E:/github/fb-react-native-forpatch/ReactAndroid/src/main/java/com/facebook/react/module/processing/BUCK
index 728ac0949..663c17003 100644
--- a/E:/github/ms-react-native-forpatch/ReactAndroid/src/main/java/com/facebook/react/module/processing/BUCK
+++ b/E:/github/fb-react-native-forpatch/ReactAndroid/src/main/java/com/facebook/react/module/processing/BUCK
@@ -2,6 +2,7 @@ load("//tools/build_defs/oss:rn_defs.bzl", "react_native_dep", "react_native_tar
 
 rn_java_annotation_processor(
     name = "processing",
+    does_not_affect_abi = True,
     processor_class = "com.facebook.react.module.processing.ReactModuleSpecProcessor",
     visibility = [
         "PUBLIC",
