diff --git a/E:/github/ms-react-native-forpatch/ReactAndroid/src/main/java/com/facebook/react/module/annotations/BUCK b/E:/github/fb-react-native-forpatch/ReactAndroid/src/main/java/com/facebook/react/module/annotations/BUCK
index 7cba50e9e..211b98157 100644
--- a/E:/github/ms-react-native-forpatch/ReactAndroid/src/main/java/com/facebook/react/module/annotations/BUCK
+++ b/E:/github/fb-react-native-forpatch/ReactAndroid/src/main/java/com/facebook/react/module/annotations/BUCK
@@ -3,6 +3,7 @@ load("//tools/build_defs/oss:rn_defs.bzl", "react_native_dep", "react_native_tar
 rn_android_library(
     name = "annotations",
     srcs = glob(["**/*.java"]),
+    required_for_source_only_abi = True,
     visibility = [
         "PUBLIC",
     ],
