diff --git "a/E:\\github\\fb-react-native-forpatch-base\\ReactCommon\\yoga\\BUCK" "b/E:\\github\\ms-react-native-forpatch\\ReactCommon\\yoga\\BUCK"
index 49ac785..4e97a42 100644
--- "a/E:\\github\\fb-react-native-forpatch-base\\ReactCommon\\yoga\\BUCK"
+++ "b/E:\\github\\ms-react-native-forpatch\\ReactCommon\\yoga\\BUCK"
@@ -12,6 +12,7 @@ cxx_library(
         "-Werror",
         "-std=c++1y",
         "-O3",
+		"-DANDROIDPLAT",
     ],
     force_static = True,
     visibility = ["PUBLIC"],
