--- "e:\\github\\fb-react-native-forpatch-base\\ReactCommon\\yoga\\BUCK"	2020-01-30 13:55:48.624582400 -0800
+++ "e:\\github\\ms-react-native-forpatch\\ReactCommon\\yoga\\BUCK"	2020-01-29 14:10:09.842926300 -0800
@@ -12,6 +12,7 @@
         "-Werror",
         "-std=c++1y",
         "-O3",
+		"-DANDROIDPLAT",
     ],
     force_static = True,
     visibility = ["PUBLIC"],
